"""
text_terminal.py — OS-level text terminal hardware.

Renders characters into the ternary system's shared VideoMemory framebuffer
using an 8×8 bitmap font.  The font is supplied as a multiprocessing.Array
so it can be generated by the GUI process (which has pygame) and shared into
CPU child processes without re-importing pygame there.

Wired up in os_gui.py (font generation) and referenced by cpu.py only through
TernarySystem.font_data / TernarySystem.text_terminal — the processor library
itself has no text-rendering logic.
"""


class TextTerminal:
    """Character-mode display terminal backed by the shared vmem framebuffer.

    Characters arrive via OUT port 1 from the ternary CPU.  Each printable
    ASCII character is rendered as an 8×8 pixel glyph into the 243×192
    video memory region.  Newline, carriage-return, backspace, and DEL are
    handled as control characters.
    """

    VRAM_W = 243
    VRAM_H = 192
    CHAR_W = 8
    CHAR_H = 8
    COLS   = VRAM_W // CHAR_W   # 30 columns
    ROWS   = VRAM_H // CHAR_H   # 24 rows
    FG     =  121   # white  (display maps  121 → 255)
    BG     = -121   # black  (display maps -121 →   0)

    def __init__(self, vmem, font_data) -> None:
        """
        vmem      — VideoMemory instance (shared across processes via _raw / lock)
        font_data — multiprocessing.Array('B', 128*8), or None to disable rendering
        """
        self.vmem      = vmem
        self.font_data = font_data
        self.cx        = 0       # cursor column  (0 .. COLS-1)
        self.cy        = 0       # cursor row     (0 .. ROWS-1)
        self._cleared  = False   # screen cleared on first character

    # ── Public ────────────────────────────────────────────────────────────────

    def write_char(self, ch: int) -> None:
        if self.font_data is None:
            return
        if not self._cleared:
            self._clear_screen()
        if ch == 10 or ch == 13:        # LF / CR
            self.cx = 0
            self.cy += 1
            if self.cy >= self.ROWS:
                self._scroll()
        elif ch == 8 or ch == 127:      # BS / DEL
            if self.cx > 0:
                self.cx -= 1
                self._draw_char(32, self.cx, self.cy)
        elif 32 <= ch < 128:
            self._draw_char(ch, self.cx, self.cy)
            self.cx += 1
            if self.cx >= self.COLS:
                self.cx = 0
                self.cy += 1
                if self.cy >= self.ROWS:
                    self._scroll()

    # ── Private ───────────────────────────────────────────────────────────────

    def _clear_screen(self) -> None:
        raw = self.vmem._raw
        bg  = self.BG
        with self.vmem.lock:
            for i in range(self.VRAM_W * self.VRAM_H):
                raw[i] = bg
        self._cleared = True

    def _scroll(self) -> None:
        raw       = self.vmem._raw
        pitch     = self.VRAM_W
        row_px    = self.CHAR_H * pitch          # pixel rows per text row
        body_px   = (self.ROWS - 1) * row_px     # everything except last row
        last_base = (self.ROWS - 1) * row_px
        bg        = self.BG
        with self.vmem.lock:
            # Shift rows 1..ROWS-1 up by one text row (bulk list copy)
            chunk = list(raw[row_px : row_px + body_px])
            raw[0 : body_px] = chunk
            raw[last_base : last_base + row_px] = [bg] * row_px
        self.cy = self.ROWS - 1

    def _draw_char(self, ch: int, col: int, row: int) -> None:
        font  = self.font_data
        raw   = self.vmem._raw
        pitch = self.VRAM_W
        px    = col * self.CHAR_W
        py    = row * self.CHAR_H
        fg    = self.FG
        bg    = self.BG
        base  = ch * 8
        size  = len(raw)
        with self.vmem.lock:
            for r in range(8):
                bits     = font[base + r]
                row_base = (py + r) * pitch + px
                for c in range(8):
                    addr = row_base + c
                    if addr < size:
                        raw[addr] = fg if (bits >> (7 - c)) & 1 else bg
